PPWStory6/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('isikegiatan', views.isikegiatan, name='isikegiatan'),
    path('daftarkegiatan', views.daftarkegiatan, name='daftarkegiatan'),
    path('peserta/<int:id>', views.peserta, name='peserta'),
]

Story4/urls.py
from django.contrib import admin
from django.urls import include, path
from Story8.views import data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Story8/data/',data),
    path('', include('main.urls')),
    path('', include('PPWStory6.urls', namespace='PPWStory6')),
    path('', include('Story7.urls', namespace='Story7')),
    path('', include('Story8.urls', namespace='Story8')),
    path('', include('Story9.urls', namespace='Story9')),
]

Story7/urls.py
from django.urls import path

from . import views

app_name = 'Story7'

urlpatterns = [
    path('Story7/', views.home, name='home'),
]

Story8/urls.py
from django.urls import path

from . import views

app_name = 'Story8'

urlpatterns = [
    path('Story8/daftar', views.home, name='home'),
]

Story9/urls.py
from django.urls import path

from . import views

app_name = 'Story9'

urlpatterns = [
    path('Story9/', views.home, name ='home'),
    path('Story9/signup/', views.signup, name='signup'),
    path('Story9/login/', views.login, name='login'),
    path('Story9/logout/', views.logout, name='logout'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('story1', views.intro, name='intro'),
    path('story3home', views.home, name='home'),
    path('story3about', views.about, name='about'),
    path('story3education', views.education, name='education'),
    path('story3experience', views.experience, name='experience'),
    path('story5isimatkul', views.isimatkul, name='isimatkul'),
    path('story5daftarmatkul', views.daftarmatkul, name='daftarmatkul'),
    path('story5hapus/<str:pk>', views.hapus, name='hapus')
]

PPWStory6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    activity = models.CharField(max_length=100)

    def __str__(self):
        return self.activity

class Peserta(models.Model):
    participant = models.CharField(max_length=50)
    act = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return self.participant

 

Story7/models.py
from django.db import models

# Create your models here.

Story8/models.py
from django.db import models

# Create your models here.

Story9/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.
TAHUN_AJAR = [
    ('2020/2021', '2020/2021 Gasal'),
    ('2020/2021', '2020/2021 Genap'),
]

class MatkulModel(models.Model):
    matkul = models.CharField(max_length=100)
    dosen = models.CharField(max_length=100)
    sks = models.IntegerField()
    tahun = models.CharField(max_length=50, choices=TAHUN_AJAR)
    ruang = models.CharField(max_length=50)
    deskripsi = models.TextField()

    def __str__(self):
        return self.matkul

        

PPWStory6/forms.py
from django import forms
from .models import Kegiatan, Peserta

class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

        labels = {
            'activity' : 'Kegiatan'
        }

class PesertaForm(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = '__all__'

        labels = {
            'participant' : 'Peserta'
        }

main/forms.py
from django import forms
from .models import MatkulModel

class MatkulForm(forms.ModelForm):
    class Meta:
        model = MatkulModel
        fields = '__all__'

        labels = {
            'matkul' : 'Matkul', 'dosen' : 'Dosen', 'sks' : 'SKS', 'tahun' : 'Tahun', 'ruang' : 'Ruang', 'deskripsi' : 'Deskripsi',
        }

PPWStory6/views.py
from django.shortcuts import render, redirect
from .forms import KegiatanForm, PesertaForm
from .models import Kegiatan, Peserta

# Create your views here.

def isikegiatan(request):
    form = KegiatanForm()

    if request.method == "POST":
        form = KegiatanForm(request.POST)
        if form.is_valid():
            post = form.save(commit=True)
            post.save()
            return redirect('/daftarkegiatan')
    else:
        form = KegiatanForm()

    return render(request, 'isikegiatan.html', {'form' : form})

def daftarkegiatan(request):
    daftar = Kegiatan.objects.all()

    context = {'obj': daftar}
    return render(request, 'daftarkegiatan.html', context)

def peserta(request, id):
    daftar = Kegiatan.objects.get(id=id)
    peserta_form = PesertaForm(request.POST, instance=daftar)

    if peserta_form.is_valid():
        submitted_data = Peserta()
        submitted_data.participant = peserta_form.cleaned_data['participant']
        submitted_data.act = peserta_form.cleaned_data['act']
        submitted_data.save()
        return redirect('/daftarkegiatan')

    else:
        peserta_form = PesertaForm()

    context = {'daftar': daftar, 'peserta_form': peserta_form}
    return render(request, 'peserta.html', context)

Story7/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'story7.html')

Story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from pip._vendor import requests

# Create your views here.
def home(request):
    response = {}
    return render(request, 'story8.html', response)

def data(request):
    argument = request.GET['q']
    url_destination = 'https://www.googleapis.com/books/v1/volumes?q=' + argument
    r = requests.get(url_destination)

    data2 = json.loads(r.content)
    return JsonResponse(data2, safe=False)

Story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as dj_login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth import logout as django_logout

# Create your views here.

def home(request):
    return render(request, 'Story9.html')
    
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
 
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            return redirect('/Story9/login')
         
        else:
            return render(request,'signup.html',{'form':form})
     
    else:
        form = UserCreationForm()
        return render(request,'signup.html',{'form':form})

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
 
        if user is not None:
            dj_login(request, user)
            return redirect('/Story9')
        else:
            form = AuthenticationForm()
            messages.error(request, 'Username atau password Anda salah')
            return render(request,'login.html',{'form':form})
     
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form':form})

def logout(request):
    django_logout(request)
    return redirect('/Story9/')

main/views.py
from django.shortcuts import render
from .forms import MatkulForm
from .models import MatkulModel
from django.shortcuts import redirect

def index(request):
    return render(request, 'main/index.html')

def intro(request):
    return render(request, 'main/intro.html')

def home(request):
    return render(request, 'main/home.html')

def about(request):
    return render(request, 'main/about.html')

def education(request):
    return render(request, 'main/education.html')

def experience(request):
    return render(request, 'main/experience.html')

def isimatkul(request):
    form = MatkulForm()

    if request.method == "POST":
        form = MatkulForm(request.POST)
        if form.is_valid():
            post = form.save(commit=True)
            post.save()
            return redirect('/story5daftarmatkul')
    else:
        form = MatkulForm()

    return render(request, 'main/isimatkul.html', {'form' : form})

def daftarmatkul(request):
    daftar = MatkulModel.objects.all()
    context = { 'obj' : daftar }
    return render(request, 'main/daftarmatkul.html', context)

def hapus(request, pk):
    daftar = MatkulModel.objects.get(id=pk)
    if request.method == "POST":
        daftar.delete()
        return redirect('/story5daftarmatkul')
    
    context = {
        'item' : daftar
    }
    return render(request, 'main/hapus.html', context)

PPWStory6/templates/daftarkegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Daftar Kegiatan</title>
<style>
    html{
        text-align: center;
        color: white;
        font-family: 'Nunito Sans', sans-serif;
    }
    .lst{
        margin-left: 5vmax;
        margin-right: 5vmax;
        line-height: 2cm;
        background-color: skyblue;
        color: darkblue;
    }
    h2{
        font-size: 2vmax;
    }
    h3{
        line-height: 1cm;
    }
    .button{
        background-color: darkblue;
        color: white;
        padding: 1vmax 1vmax;
        text-decoration: none;
        font-weight: bolder;
        margin: 1cm;
    }
    p{
        margin-top: 2cm;
        margin-bottom: 2cm;
    }
</style>

{% endblock meta %}

{% block content %}
    <div class="navigation">
        <ul class="nav justify-content-start">
            <h1>RD</h1>
        </ul>
    </div>
    <div class="container">
        <h2>Daftar Kegiatan:</h2>
        <form method="POST">
            {% for daftar in obj %}

                <div class="lst">
                    <h2>{{ daftar.activity }}</h2>
                    {% for i in daftar.peserta %}
                        <h3>{{ i.participant }}</h3>
                    {% endfor %}
                    <a href="{% url 'PPWStory6:peserta' daftar.id %}" class="button">Tambah Peserta</a></td>
                </div>     
            {% endfor %}
            <br>   
            <p><a href="{% url 'PPWStory6:isikegiatan' %}" class="button">Tambah Kegiatan</a></p>
        </form>
    </div>
    
{% endblock content %}

Story9/templates/Story9.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Story 9</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% endblock meta %}

{% block content %}
<div class="navigation">
    <ul class="nav justify-content-start">
        <h1>RD</h1>
        {% if user.is_authenticated %}
            <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Hi, {{ user.get_username }}</a>
            <a class="nav-link" href="{% url 'Story9:logout' %}"><img src="https://icon-library.com/images/logout-icon-png/logout-icon-png-3.jpg" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Logout</a>
        {% else %}
            <a class="nav-link"><img src="https://peopleshub.org/wp-content/uploads/2018/04/person-icon-white.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Hi, Guest</a>
            <a class="nav-link" href="{% url 'Story9:login' %}"><img src="https://icon-library.com/images/11a7acda9d.png" style="width: 30px; height: 30px; vertical-align:bottom; margin-top: -14px;">Login</a>
        {% endif %}
    </ul>
</div>

<div class="banner">
    <div class="bann">
        {% if user.is_authenticated %}
            <h1>Selamat Datang, {{ user.get_username }} !</h1>
        {% else %}
            <h1>Selamat Datang, Guest !</h1>
        {% endif %}
        <p>Sudah tidak terasa bahwa kita telah sejauh ini menjalani perkuliahan PPW yang mana kita sudah mencapai Story 9 !!!</p><br><br>
        <a class="button1" href="#liatstory">Daftar Story</a>
    </div>
</div>
<div class="liatstory">
    <h1>Daftar Story</h1>
    <p>Berikut daftar story-story sebelumnya yang telah dikerjakan oleh Ryan Dirga :</p>
    <div id="liatstory">
        {% if user.is_authenticated %}
            <a class="button1" href="{% url 'main:intro' %}">Story 1</a>
            <a class="button1" href="https://www.figma.com/proto/HEsdpXoxt6IFBNFBtF17u3/PEPEWSTORY2?node-id=1%3A3&scaling=min-zoom">Story 2</a>
            <a class="button1" href="{% url 'main:home' %}">Story 4</a>
            <a class="button1" href="{% url 'main:daftarmatkul' %}">Story 5</a>
            <a class="button1" href="{% url 'PPWStory6:daftarkegiatan' %}">Story 6</a>
            <a class="button1" href="{% url 'Story7:home' %}">Story 7</a>
            <a class="button1" href="{% url 'Story8:home' %}">Story 8</a>
        {% else %}
            <a class="button1" href="{% url 'Story9:login' %}">Story 1</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 2</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 4</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 5</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 6</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 7</a>
            <a class="button1" href="{% url 'Story9:login' %}">Story 8</a>
        {% endif %}
    </div>
</div>

{% endblock content %}

Story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Log In</title>
{% endblock meta %}

{% block content %}
<div class="navigation">
    <ul class="nav justify-content-start">
        <h1>RD</h1>
    </ul>
</div>
<div class="signin">
    <form id="signin" method='POST'>
        <h2>Log In</h2><br>
        {% csrf_token %}
        {{form.as_p}}
        <br><br>
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">{{ message }}</div>
                <br><br>
            {% endif %}
        {% endfor %}

        <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type = "submit" value = "Log in">
        <br><br>
        <p>Belum punya akun ? Sign up dulu di <a class="sinisignup" href = "{% url 'Story9:signup' %}">sini</a></p><br>
    </form>
</div>
{% endblock content %}

Story9/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Sign Up</title>
{% endblock meta %}

{% block content %}
<div class="navigation">
    <ul class="nav justify-content-start">
        <h1>RD</h1>
    </ul>
</div>
<div class="signup">
    <form id="signup" method='POST'>
        <h2>Sign Up</h2><br>
        {% csrf_token %}
        {% for field in form %}
            <p>
            {{ field.label_tag }}<br>
            <p class="inputan">{{ field }}</p>
            {% for error in field.errors %}
                <p style="color: rgb(179, 0, 0)">{{ error }}</p>
            {% endfor %}
            </p>
        {% endfor %}
        <br>
        <input style="background-color: rgb(17, 17, 61); color: white; margin-left: 0px; padding: 8px 10px; font-size: 16px;" type="submit" value = "Sign up">
        <br><br>
        <p>Sudah punya akun? Langsung log in di <a class="sinilogin" href="{% url 'Story9:login' %}">sini</a></p>
    </form>
    
</div>
{% endblock content %}

main/templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-About</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock meta %}

{% block content %}
    <div class="navigation">
        <ul class="nav justify-content-start">
            <h1>RD</h1>
            <a class="nav-link" href="{% url 'main:intro' %}">STORY 1</a>
            <a class="nav-link" href="{% url 'main:home' %}">HOME</a>
            <a class="nav-link" href="{% url 'main:education' %}">EDUCATION</a>
            <a class="nav-link" href="{% url 'main:experience' %}">EXPERIENCE</a>
            <a class="nav-link" href="{% url 'main:daftarmatkul' %}">MATA KULIAH</a>
        </ul>
    </div>
    <div class="main-about">
        <div class="row">
            <div class="col align-self-start">
                <p class="image"><img src="{% static 'img/myphoto.jpg' %}" width="220" height="220"></p>
            </div>
            <div class="col align-self-center">
                <p class="name">Ryan Dirga</p>
                <p class="des">Information System</p>
            </div>
        </div>
        <div class="info">
            <br>
            <p class="a">Nama Lengkap:</p><p class="b">Ryan Dirga Aidil Hakim</p><br>
            <p class="a">Tempat / tanggal lahir:</p><p class="b">Pekanbaru, 27 Desember 2000</p><br>
            <p class="a">Alamat:</p><p class="b">Jalan Mandor Basir 1 No 8R (Depok Permai Regency Kukusan), Kukusan, Beji, Depok, Jawa Barat, Kode Pos 16425</p><br>
            <p class="a">Tempat Kuliah:</p><p class="b">Fakultas Ilmu Komputer Universitas Indonesia</p><br>
            <p class="a">NPM:</p><p class="b">1907306741</p>
        </div>
    </div>
{% endblock content %}

main/templates/main/daftarmatkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Daftar Matkul</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<style>
    body{
        background-color: rgb(17, 17, 61);
        color: white;
        font-family: 'Nunito Sans', sans-serif;
        text-align: center;
    }
    h2{
        margin-top: 2cm;
        font-weight: bolder;
        font-size: 5vmin;
    }
    .tabel{
        margin-top: 2cm;
        width: 100%;
        line-height: 1cm;
    }
    .button, .button1{
        
        font-family: 'Nunito Sans', sans-serif;
        font-weight: bolder;
        text-align: center;
        text-decoration: none;
        margin: 2cm;
    }
    .button{
        font-size: 16px;
        padding: 8px 20px;
    }
    .button1{
        background-color: rgb(103, 170, 233);
        color: rgb(17, 17, 61);
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 18px;
        padding: 15px 25px;
    }

</style>
{% endblock meta %}

{% block content %}
    <div class="navigation">
        <ul class="nav justify-content-start">
            <h1>RD</h1>
            <a class="nav-link" href="{% url 'main:intro' %}">STORY 1</a>
            <a class="nav-link" href="{% url 'main:home' %}">HOME</a>
            <a class="nav-link" href="{% url 'main:about' %}">ABOUT ME</a>
            <a class="nav-link" href="{% url 'main:education' %}">EDUCATION</a>
            <a class="nav-link" href="{% url 'main:experience' %}">EXPERIENCE</a>
        </ul>
    </div>
    <div class="container">
        <h2>Daftar Matkul yang telah ditambahkan:</h2>
        <form method="POST">
            <table class="tabel" border="4">
                <thead>
                    <tr>
                        <th>Mata Kuliah</th>
                        <th>Dosen</th>
                        <th>Jumlah SKS</th>
                        <th>Tahun Ajaran</th>
                        <th>Ruang</th>
                        <th>Deskripsi</th>
                        <th>Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    {% for daftar in obj %}
                    <tr>
                        <td>{{ daftar.matkul }}</td>
                        <td>{{ daftar.dosen }}</td>
                        <td>{{ daftar.sks }}</td>
                        <td>{{ daftar.tahun }}</td>
                        <td>{{ daftar.ruang }}</td>
                        <td>{{ daftar.deskripsi }}</td>
                        <td><a href="{% url 'main:hapus' daftar.id %}" class="button">Hapus</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <p><a href="{% url 'main:isimatkul' %}" class="button1">Tambah Mata Kuliah</a></p>
        </form>
    </div>
{% endblock content %}

main/templates/main/education.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Education</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock meta %}
    
{% block content %}
  <div class="navigation">
        <ul class="nav justify-content-start">
            <h1>RD</h1>
            <a class="nav-link" href="{% url 'main:intro' %}">STORY 1</a>
            <a class="nav-link" href="{% url 'main:home' %}">HOME</a>
            <a class="nav-link" href="{% url 'main:about' %}">ABOUT ME</a>
            <a class="nav-link" href="{% url 'main:experience' %}">EXPERIENCE</a>
            <a class="nav-link" href="{% url 'main:daftarmatkul' %}">MATA KULIAH</a>
        </ul>
    </div>
    <div class="education">
        <p class="c">Riwayat Pendidikan:</p><br>
        <p class="a">Universitas Indonesia</p><p class="b">2019-sekarang</p><br>
        <p class="a">SMA Islam Al-Azhar 1</p><p class="b">2016-2019</p><br>
        <p class="a">SMP Islam Al-Azhar 1</p><p class="b">2013-2016</p><br>
        <p class="a">SD Islam Darussalam Pekayon</p><p class="b">2007-2013</p>
    </div>
{% endblock content %}

main/templates/main/experience.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Experience</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock meta %}
    
{% block content %}
  <div class="navigation">
        <ul class="nav justify-content-start">
            <h1>RD</h1>
            <a class="nav-link" href="{% url 'main:intro' %}">STORY 1</a>
            <a class="nav-link" href="{% url 'main:home' %}">HOME</a>
            <a class="nav-link" href="{% url 'main:about' %}">ABOUT ME</a>
            <a class="nav-link" href="{% url 'main:education' %}">EDUCATION</a>
            <a class="nav-link" href="{% url 'main:daftarmatkul' %}">MATA KULIAH</a>
        </ul>
    </div>
    <div class="experience">
        <p class="c">Pengalaman:</p><br>
        <p class="a">Staf di Biro Syiar Kreatif</p><p class="b">Forum Ukhuwah dan Kajian Islam</p><p class="b">(Februari 2020 - sekarang)</p><br>
        <p class="a">Mentor</p><p class="b">PMB Fasilkom UI</p><p class="b">(Juli 2020 - sekarang)</p><br>
    </div>
{% endblock content %}

main/templates/main/hapus.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Hapus</title>
<style>
    body{
        padding-top: 100px;
        text-align: center;
        color: white;
        font-family: 'Nunito Sans', sans-serif;
    }
    .button, .inp{
        background-color: rgb(103, 170, 233);
        border-style: none;
        color: rgb(17, 17, 61);
        padding: 12px 25px;
        font-family: 'Nunito Sans', sans-serif;
        font-size: 18px;
        text-decoration: none;
    }
    .button{
        margin-right: 3cm;
    }
</style>

{% endblock meta %}

{% block content %}
    <h2>Apakah Anda yakin ingin menghapus mata kuliah {{ item }} ?</h2><br>
    <form action="{% url 'main:hapus' item.id %}" method="POST">
        
        {% csrf_token %}
        <a href="{% url 'main:daftarmatkul' %}" class="button">Tidak</a>
        <input class="inp" type="submit" value="Iya">
    </form>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>RD-Home</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
{% endblock meta %}

{% block content %}
  <div class="navigation">
            <ul class="nav justify-content-start">
                <h1 class="rd">RD</h1>
                <a class="nav-link" href="{% url 'main:intro' %}">STORY 1</a>
                <a class="nav-link" href="{% url 'main:about' %}">ABOUT ME</a>
                <a class="nav-link" href="{% url 'main:education' %}">EDUCATION</a>
                <a class="nav-link" href="{% url 'main:experience' %}">EXPERIENCE</a>
                <a class="nav-link" href="{% url 'main:daftarmatkul' %}">MATA KULIAH</a>
            </ul>
        </div>
        <div class="welcome">
            <h2 class="p-home">Welcome !</h2>
            <img src="{% static 'img/myphoto.jpg' %}" width="300px" height="300px">
        </div>
        <div class="footer">
            <h5 class="x">My contacts:</h5>
            <h5 class="x"><img src="{% static 'img/logo line.png' %}" width="30" height="30" style="vertical-align:middle; margin:10px"> ryandirgaa</h5>
            <h5 class="x"><img src="{% static 'img/logo wa.png' %}" width="30" height="30" style="vertical-align:middle; margin:10px"> 081287364751</h5>
            <h5 class="x"><img src="{% static 'img/gmail.png' %}" width="30" height="30" style="vertical-align:middle; margin:10px"> ryandirgaaidilhakim@gmail.com</h5>
        </div>
{% endblock content %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Introduction</title>
<style>
    .x, .y, .z{
        text-align: center;
        margin-bottom: 50px;
        color: white;
        font-family: 'Nunito Sans', sans-serif;
    }
    .x{
        margin-top: 200px;
        font-size: 30px;
    }
    .y{
        font-size: 25px;
    }
    .button{
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: rgb(103, 170, 233);
        color: rgb(17, 17, 61);
        font-family: 'Nunito Sans', sans-serif;
        font-weight: bolder;
        font-size: 18px;
        padding: 15px 25px;
        text-align: center;
        text-decoration: none;
        margin: 2cm;
    }
</style>
{% endblock meta %}


{% block content %}
    <h6 class="x">Halo, selamat datang di RD !</h6>
    <p class="y">Silakan klik salah satu  di bawah ini untuk melihat story 1 atau story 3 saya :</p>
    <p class="z"><a href="{% url 'main:intro' %}" class="button">Go to Story 1</a></p>
    <p class="z"><a href="{% url 'main:home' %}" class="button">Go to Story 3</a></p>
    <p class="z"><a href="{% url 'Story7:home' %}" class="button">Go to Story 7</a></p>
     
{% endblock content %}